[package]
name = "disqalculate"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0"
poise = "0.6.1"
tokio = { version = "*", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
cxx-build = "1.0"
pkg-config = "*"
