[package]
name = "disqalculate"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "*"
paste = "1.0.15"
poise = "*"
tokio = { version = "*", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
cxx-build = "*"
pkg-config = "*"
