[package]
name = "dwalk"
version = "0.1.0"
edition = "2021"

[dependencies]
color-print = "0.3.7"
rand = "0.9.0"
tokio = { version = "*", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
